<Project>
  <PropertyGroup>
    <VersionPrefix>0.4.0</VersionPrefix>
    <Authors>sjvrensburg</Authors>
    <Copyright>Copyright © 2026 Stefan van Rensburg</Copyright>
    <RepositoryUrl>https://github.com/sjvrensburg/RailReaderLite.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
